#!/bin/sh
set -e

UUID=$(/etc/fos/node_uuid.sh)
id -u fos  >/dev/null 2>&1 ||  sudo useradd -r -s /bin/false fos
usermod -aG sudo fos
echo "fos      ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers > /dev/null
sh -c "echo $UUID | xargs -i  jq  '.configuration.nodeid = \"{}\"' /etc/fos/plugins/plugin-os-linux/linux_plugin.json > /tmp/os_plugin.tmp && mv /tmp/os_plugin.tmp /etc/fos/plugins/plugin-os-linux/linux_plugin.json"
pip3 install psutil netifaces mvar
mkdir -p /var/fos
chown fos:fos /var/fos
#DEBHELPER#
systemctl daemon-reload
exit 0

