#!/bin/sh
set -e
usermod -aG lxd fos
UUID=$(/etc/fos/node_uuid.sh)
sh -c "echo $UUID | xargs -i  jq  '.configuration.nodeid = \"{}\"' /etc/fos/plugins/plugin-fdu-lxd/LXD_plugin.json > /tmp/fdu_plugin.tmp && mv /tmp/fdu_plugin.tmp /etc/fos/plugins/plugin-fdu-lxd/LXD_plugin.json"
pip3 install pylxd mvar jinja2 packaging pyangbind
chown fos:fos -R /var/fos
systemctl daemon-reload
#DEBHELPER#
exit 0

