#!/bin/sh
set -e

UUID=$(/etc/fos/node_uuid.sh)
sh -c "echo $UUID | xargs -i  jq  '.configuration.nodeid = \"{}\"' /etc/fos/plugins/plugin-fdu-native/native_plugin.json > /tmp/fdu_plugin.tmp && mv /tmp/fdu_plugin.tmp /etc/fos/plugins/plugin-fdu-native/native_plugin.json"
pip3 install psutil mvar jinja2 pyangbind
chown fos:fos -R /var/fos
systemctl daemon-reload
#DEBHELPER#
exit 0

