#!/bin/sh
set -e
usermod -aG kvm fos
usermod -aG libvirt fos
UUID=$(/etc/fos/node_uuid.sh)
sh -c "echo $UUID | xargs -i  jq  '.configuration.nodeid = \"{}\"' /etc/fos/plugins/plugin-fdu-kvm/KVM_plugin.json > /tmp/fdu_plugin.tmp && mv /tmp/fdu_plugin.tmp /etc/fos/plugins/plugin-fdu-kvm/KVM_plugin.json"
pip3 install mvar libvirt-python jinja2
chown fos:fos -R /var/fos
systemctl daemon-reload
#DEBHELPER#
exit 0

