#!/bin/sh
set -e

UUID=$(/etc/fos/node_uuid.sh)
sh -c "echo $UUID | xargs -i  jq  '.configuration.nodeid = \"{}\"' /etc/fos/plugins/plugin-net-linuxbridge/linuxbridge_plugin.json > /tmp/net_plugin.tmp && mv /tmp/net_plugin.tmp /etc/fos/plugins/plugin-net-linuxbridge/linuxbridge_plugin.json"
pip3 install psutil netifaces mvar
chown fos:fos -R /var/fos
systemctl daemon-reload
#DEBHELPER#
exit 0

